version: '3.9'
services:

  eureka:
    build:
      context: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - box-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  userservice:
    build:
      context: ./userservice
    container_name: userservice
    environment:
      - MONGO_URI=mongodb+srv://admin:abc123password@assessmentcluster.1zkdesg.mongodb.net/userservice_db?retryWrites=true&w=majority&appName=assessmentcluster
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    ports:
      - "8081:8080"
    depends_on:
      eureka:
        condition: service_healthy
    networks:
      - box-network

  boxservice:
    build:
      context: ./boxservice
    container_name: boxservice
    environment:
      - MONGO_URI=mongodb+srv://admin:abc123password@assessmentcluster.1zkdesg.mongodb.net/boxservice_db?retryWrites=true&w=majority&appName=assessmentcluster
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    ports:
      - "8082:8080"
    depends_on:
      eureka:
        condition: service_healthy
    networks:
      - box-network

  itemservice:
    build:
      context: ./itemservice
    container_name: itemservice
    environment:
      - MONGO_URI=mongodb+srv://admin:abc123password@assessmentcluster.1zkdesg.mongodb.net/itemservice_db?retryWrites=true&w=majority&appName=assessmentcluster
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    ports:
      - "8083:8080"
    depends_on:
      eureka:
        condition: service_healthy
    networks:
      - box-network

networks:
  box-network:
    driver: bridge