server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: boxservice
          uri: lb://boxservice
          predicates:
            - Path=/api/box/**
          filters:
            - StripPrefix=1

        - id: itemservice
          uri: lb://itemservice
          predicates:
            - Path=/api/item/**
          filters:
            - StripPrefix=1

        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,gateway,routes
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true